//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelance.AuditApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int ActionId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public byte[] UploadedFile { get; set; }
        public string ActionDescription { get; set; }
        public string ClosedReason { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public byte[] ClosedFile { get; set; }
        public string RaisedBy { get; set; }
    }
}
