//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelance.AuditApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuditConnection : DbContext
    {
        public AuditConnection()
            : base("name=AuditConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserProject> UserProjects { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<AspectItem> AspectItems { get; set; }
        public DbSet<ProjectAspect> ProjectAspects { get; set; }
        public DbSet<Action> Actions { get; set; }
        public DbSet<Result> Results { get; set; }
        public DbSet<Project> Projects { get; set; }
    }
}
