//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelance.AuditApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAspect
    {
        public ProjectAspect()
        {
            this.AspectItems = new HashSet<AspectItem>();
        }
    
        public int ProjectAspectsID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Aspect { get; set; }
    
        public virtual ICollection<AspectItem> AspectItems { get; set; }
        public virtual Project Project { get; set; }
    }
}
